In [3]:
import numpy as np
import tensorflow as tf

In [4]:
hello = tf.constant('Hello, TensorFlow!') 

sess = tf.InteractiveSession() 
print(sess.run(hello))

b'Hello, TensorFlow!'


In [17]:
zeros_tensor = tf.zeros([3, 3])

print(zeros_tensor.eval())
print(zeros_tensor)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
Tensor("zeros_9:0", shape=(3, 3), dtype=float32)


In [18]:
v = tf.Variable(zeros_tensor)

In [26]:
sess.run(v.initializer)
v.eval()

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)